import type { Metadata } from "next";
import { IBM_Plex_Sans_JP, Poppins } from "next/font/google";
import "./reset.css";
import "./globals.css";

const ibmPlexSansJP = IBM_Plex_Sans_JP({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  weight: ["500"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "arrow2nd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${ibmPlexSansJP.className} ${poppins.variable}`}>
      <body>
        {children}
        <footer>(c) arrow2nd</footer>
      </body>
    </html>
  );
}
